### ISSUE TITLE
Doesn't work when the ruby project is in a subfolder of the main project

### ISSUE THREAD

**Issue by fazo96** [simoleone/rubymine-sorbet-lsp#3]
This notification appears when I try using the plugin: Sorbet: `Sorbet's language server requires a single input directory. However, 0 are configured: []`

Taking a look at the code of the extension, it seems that it will run `srb tc --lsp` on the root directory of the RubyMine project.

In my case unfortunately the ruby project is in a subfolder called `backend` of the main project. I was able to work around this by creating a sorbet config file for the root folder of the project, and it seems to work, but it's not ideal

Would it be possible to expose an option for this plugin to run in a subfolder?

**Comment by simoleone** [comment]
Hey! I'll look into it! I'd like to have the plugin "just work" for the most common cases, and it's probably not that unusual to have in a subdirectory like you're describing. Just to check - the subdirectory in this case is showing up as a ruby project/module/whatever already, as in IntelliJ or RubyMine has already figured out that it's a separate ruby project root?

**Comment by simoleone** [comment]
Hey @fazo96 ! I finally got a chance to look at this. Instead of using the project root we'll use the directory we found the module's Gemfile in. At least this worked for a dummy project I mocked up to try it out.

I just pushed version 1.6 of the plugin with this fix in it. It'll appear as an update as soon as Jetbrains approves it. Let me know if it works for you!
